current_version: 2
versions:
  1:
    description: Legacy noon temperature schema with root-level temperature map
    required:
      - place
      - place.name
      - place.lat
      - place.lon
      - place.timezone
      - place.grid_lat
      - place.grid_lon
    required_any_of:
      - [temp_map_v1, noon_temperatures, temperatures]
    primary_data_path: noon_temperatures
    legacy_data_paths:
      - temperatures
  2:
    description: Noon temperature cache schema with explicit variable metadata
    required:
      - schema_version
      - place
      - variables
      - data
      - place.name
      - place.lat
      - place.lon
      - place.timezone
      - place.grid_lat
      - place.grid_lon
    data_key: data
    variables_key: variables
    primary_variable: noon_temp_C
    measure_cache_vars:
      noon_temperature: noon_temp_C
      daily_precipitation: daily_precip_mm
      daily_solar_radiation_energy: daily_solar_energy_MJ_m2
    measure_value_columns:
      noon_temperature: temp_C
      daily_precipitation: precip_mm
      daily_solar_radiation_energy: solar_energy_MJ_m2
    migration:
      from_version: 1
      field_mappings:
        data.noon_temp_C:
          source_candidates:
            - temp_map_v1
            - noon_temperatures
            - temperatures
    variables:
      noon_temp_C:
        units: C
        source_variable: 2m_temperature
        source_dataset: reanalysis-era5-single-levels
        temporal_definition: daily_local_noon
        precision: 2
      daily_precip_mm:
        units: mm
        source_variable: total_precipitation
        source_dataset: reanalysis-era5-single-levels
        temporal_definition: daily_total_local
        precision: 2
      daily_solar_energy_MJ_m2:
        units: MJ/m2
        source_variable: surface_solar_radiation_downwards
        source_dataset: reanalysis-era5-single-levels
        temporal_definition: daily_total_local
        precision: 2
